using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WSAInstallTool
{
    class ApkShellDetection
    {
        public static Dictionary<string, string> sMap = new Dictionary<string, string>()
         {
            {"libnqshield.so", "国信灵通" },
            {"libvenSec.so", "启明星辰"},
            {"libvenustech.so", "启明星辰"},
            {"libchaosvmp.so", "娜迦加固"},
            {"libddog.so", "娜迦加固"},
            {"libfdog.so", "娜迦加固"},
            {"libedog.so", "娜迦加固（企业版）"},
            {"libexec.so", "爱加密"},
            {"libexecmain.so", "爱加密"},
            {"ijiami.dat", "爱加密"},
            {"ijiami.ajm", "爱加密"},
            {"libsecexe.so", "梆梆安全"},
            {"libsecmain.so", "梆梆安全"},
            {"libSecShell.so", "梆梆安全"},
            {"libDexHelper.so", "梆梆安全（企业版）"},
            {"libDexHelper-x86.so", "梆梆安全（企业版）"},
            {".appkey", "360加固"},
            {"libprotectClass.so", "360加固"},
            {"libjiagu.so", "360加固"},
            {"libjiagu_ls.so", "360加固"},
            {"libjiagu_x86.so", "360加固"},
            {"libjiagu_a64.so", "360加固"},
            {"libjiagu_x64.so", "360加固"},
            {"libjiagu_art.so", "360加固"},
            {"libjgdtc.so", "360加固"},
            {"libjgdtc_x86.so", "360加固"},
            {"libjgdtc_a64.so", "360加固"},
            {"libjgdtc_x64.so", "360加固"},
            {"libjgdtc_art.so", "360加固"},
            {"libegis.so", "通付盾"},
            {"libNSaferOnly.so", "通付盾"},
            {"libapssec.so", "盛大加固"},
            {"librsprotect.so", "瑞星加固"},
            {"libitsec.so", "海云安加固"},
            {"libnqshield.so", "网秦加固"},
            {"libbaiduprotect.so", "百度加固"},
            {"libbaiduprotect_x86.so", "百度加固"},
            {"libbaiduprotect_art.so", "百度加固"},
            {"baiduprotect1.jar", "百度加固"},
            {"aliprotect.dat", "阿里聚安全"},
            {"libsgmain.so", "阿里聚安全"},
            {"libfakejni.so", "阿里聚安全"},
            {"libzuma.so", "阿里聚安全"},
            {"libzumadata.so", "阿里聚安全"},
            {"libpreverify1.so", "阿里聚安全"},
            {"libdemolishdata.so", "阿里聚安全"},
            {"libdemolish.so", "阿里聚安全"},
            {"libsgsecuritybody.so", "阿里聚安全"},
            {"libmobisec.so", "阿里聚安全"},
            {"libtup.so", "腾讯乐固"},
            {"liblegudb.so", "腾讯乐固"},
            {"libshella", "腾讯乐固"},
            {"libshellx", "腾讯乐固"},
            {"mix.dex", "腾讯乐固"},
            {"mixz.dex", "腾讯乐固"},
            {"libshell-super.2019.so", "腾讯云移动应用安全"},
            {"libBugly-yaq.so", "腾讯云移动应用安全"},
            {"libzBugly-yaq.so", "腾讯云移动应用安全"},
            {"tosversion", "腾讯云移动应用安全"},
            {"libshellx-super.2019.so", "腾讯云移动应用安全"},
            {"tosprotection", "腾讯云移动应用安全"},
            {"00O000ll111l.dex", "腾讯云移动应用安全"},
            {"000O00ll111l.dex", "腾讯云移动应用安全）"},
            {"0000000lllll.dex", "腾讯云移动应用安全"},
            {"00000olllll.dex", "腾讯云移动应用安全"},
            {"0OO00l111l1l", "腾讯云移动应用安全"},
            {"o0oooOO0ooOo.dat", "腾讯云移动应用安全"},
            {"t86", "腾讯云移动应用安全"},
            {"libtosprotection.x86.so", "腾讯云移动应用安全"},
            {"libtosprotection.armeabi.so", "腾讯云移动应用安全"},
            {"libtosprotection.armeabi-v7a.so", "腾讯云移动应用安全"},
            {"libnesec.so", "网易易盾"},
            {"libAPKProtect.so", "APKProtect"},
            {"libkwscmm.so", "几维安全"},
            {"libkwscr.so", "几维安全"},
            {"libkwslinker.so", "几维安全"},
            {"libx3g.so", "顶像科技"},
            {"libuusafe.jar.so", "UU安全"},
            {"libuusafe.so", "UU安全"},
            {"libuusafeempty.so", "UU安全"},
            {"mogosec_classes", "中国移动加固"},
            {"mogosec_data", "中国移动加固"},
            {"mogosec_dexinfo", "中国移动加固"},
            {"mogosec_march", "中国移动加固"},
            {"libcmvmp.so", "中国移动加固"},
            {"libmogosec_dex.so", "中国移动加固"},
            {"libmogosec_sodecrypt.so", "中国移动加固"},
            {"ibmogosecurity.so", "中国移动加固"},
            {"libreincp.so", "珊瑚灵御"},
            {"libreincp_x86.so", "珊瑚灵御"},
            {"jiagu_data.bin", "apktoolplus"},
            {"sign.bin", "apktoolplus"},
            {"libapktoolplus_jiagu.so", "apktoolplus"},
         };
    }


}
